name             'scpr-consul-haproxy'
maintainer       'Southern California Public Radio'
maintainer_email 'erichardson@scpr.org'
license          'all_rights'
description      'Installs/Configures scpr-consul-haproxy'
long_description 'Installs/Configures scpr-consul-haproxy'
version          '0.4.2'

depends 'apt'
depends 'scpr-consul'
depends 'consul-template'
